name: 'Install dependencies'
description: "Build python package on python"

runs:
  using: "composite"
  steps:
    - name: Replace Token
      shell: bash
      run: |
        ls -l
        echo *********************databricks.yml
        cat databricks.yml
        echo *********************Makefile
        cat Makefile
        echo *********************noxfile.py
        cat noxfile.py
        echo *********************pyproject.toml
        cat pyproject.toml
        echo *********************sonar-project.properties
        cat sonar-project.properties

    - name: Install poetry packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pipx install poetry==1.8.2

    - name: Setup python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64
        cache: 'poetry'
        cache-dependency-path: '**/poetry.lock'

    - name: Install python packages
      shell: bash
      run: poetry install --no-interaction
      