name: 🚀 CI/CD Main Workflow

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize
on:
  workflow_dispatch:

permissions: write-all

jobs:
  # validation_and_unit_tests:
  #   name: 'Validation checks and unit tests'
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: 'Checkout repository'
  #       uses: actions/checkout@v4
  #     - name: 'Install dependencies'
  #       uses: ./.github/actions/install-dependencies
      # - name: 'Run validation checks'
      #   uses: ./.github/actions/validation
      # - name: 'Run unit tests & Sonar analysis'
      #   uses: ./.github/actions/unit-test
      #   with:
      #     target_directory: ./tests/unit
      #     python_version: '3.9'
      #     SONAR_URL: ${{ secrets.SONAR_URL }}
      #     SONARQUBE_SCAN_TOKEN: ${{ secrets.SONARQUBE_SCAN_TOKEN }}

  deploy_prep_prod:
    name: 'Deploy to pre-prod'
    environment: pre-prod
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: Replace PROJECT_NAME
        shell: bash
        run: |
          ls -l
          find . -type f -not -path "./.github/*" -exec sed -i "s/__PROJECT_NAME__/${{  vars.PROJECT_NAME }}/g" {} +
          echo *********************databricks.yml
          cat databricks.yml
      - name: Replace DATABRICKS_URL
        shell: bash
        run: |
          ls -l
          sed -i "s/__DATABRICKS_URL__/${{ vars.DATABRICKS_URL }}/g" databricks.yml
          echo *********************databricks.yml
          cat databricks.yml
      - name: Replace SPN
        shell: bash
        run: |
          ls -l
          sed -i "s/__SPN__/${{ vars.SPN }}/g" databricks.yml
          echo *********************databricks.yml
          cat databricks.yml
      - name: 'Install dependencies'
        uses: ./.github/actions/install-dependencies
      - name: 'Deploy to prep-prod'
        uses: ./.github/actions/deploy
        with:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_ENVIRONMENT: pre-prod



  run_integration_tests:
    name: 'Run integration tests'
    environment: pre-prod
    runs-on: ubuntu-22.04
    needs: [deploy_prep_prod]
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: Replace Token
        shell: bash
        run: |
          ls -l
          sed -i "s/__DATABRICKS_URL__/${{ vars.DATABRICKS_URL }}/g" databricks.yml
          sed -i "s/__SPN__/${{ vars.SPN }}/g" databricks.yml
          find . -type f -not -path "./.github/*" -exec sed -i "s/__PROJECT_NAME__/${{  vars.PROJECT_NAME }}/g" {} +
          echo *********************databricks.yml
          cat databricks.yml
          echo *********************Makefile
          cat Makefile
          echo *********************noxfile.py
          cat noxfile.py
          echo *********************pyproject.toml
          cat pyproject.toml
          echo *********************sonar-project.properties
          cat sonar-project.properties
      - name: 'Install dependencies'
        uses: ./.github/actions/install-dependencies

      - name: 'Run integration test'
        uses: ./.github/actions/run
        with:
          asset_to_run: dataSquad_ingestion_row_to_curated
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          databricks_environment: pre-prod

