name: CI/CD Pipeline for Databricks

on:
  push:
    branches:
      - 'main'

permissions: write-all

jobs:
  update-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Python
      uses: actions/setup-python@v5
      with:
       python-version: '3.13'
       cache: 'pip' # caching pip dependencies

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Configure Databricks CLI
      run: databricks configure --host ${{ secrets.DATABRICKS_HOST }} --token ${{ secrets.DATABRICKS_TOKEN_HOST }}

    - name: Import Directory to Databricks
      run: databricks workspace import_dir . Workspace/git/test1
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_HOST }}
